version: '3.8'
services:
  postgres-sensor-container:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=sensor_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./library:/var/lib/postgresql/data
volumes:
  postgres-sensor-container:
    driver: local