--liquibase formatted sql

--changeset leanid:create basic tables
CREATE TABLE sensor (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE measurement (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value int NOT NULL,
    raining boolean NOT NULL,
    sensor_id int REFERENCES sensor(id) ON DELETE CASCADE
);
--rollback drop table sensor;
--rollback drop table measurement;